# Generated by Django 2.1.3 on 2018-11-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('estacionamiento', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('disponible', models.BooleanField()),
            ],
        ),
    ]
